# Import Statements

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

##### Preparate datasets

In [5]:
ue = pd.read_csv("data/subsidioDesemprego_2004_01_2025_12.csv")

ue["MONTH"] = pd.to_datetime(ue["Time"]) # convert Time to datetime
ue["YEAR"] = ue["MONTH"].dt.year # Create YEAR column
ue = ue.rename(columns={"subsídio de desemprego": "UE_BENEFITS_WEB_SEARCH_PT"}) # rename column

annual = ue.groupby("YEAR")["UE_BENEFITS_WEB_SEARCH_PT"].mean().reset_index() # Aggregate by year (avg)

print(annual)

    YEAR  UE_BENEFITS_WEB_SEARCH_PT
0   2004                   0.000000
1   2005                   8.333333
2   2006                  12.250000
3   2007                   8.916667
4   2008                  16.833333
5   2009                  17.083333
6   2010                  16.416667
7   2011                  25.000000
8   2012                  37.500000
9   2013                  33.500000
10  2014                  27.250000
11  2015                  29.583333
12  2016                  23.916667
13  2017                  24.833333
14  2018                  24.000000
15  2019                  29.083333
16  2020                  65.500000
17  2021                  63.500000
18  2022                  51.583333
19  2023                  49.250000
20  2024                  51.166667
21  2025                  55.000000

Search interest over a specific time period, displayed on a relative scale from 0 to 100, where 100 signifies the peak interest for the time period of the chart. A value of 50 indicates half the popularity of the peak, and 0 suggests insufficient data.

In [17]:
unemp = pd.read_csv("data/taxaDesemprego_2004_2025.csv")
unemp.columns = ["YEAR", "UNRATE_PT"]

df_unemployment = pd.merge(annual, unemp, on="YEAR", how="inner")
df_unemployment.head()

   YEAR  UE_BENEFITS_WEB_SEARCH_PT  UNRATE_PT
0  2004                   0.000000        6.6
1  2005                   8.333333        7.6
2  2006                  12.250000        7.6
3  2007                   8.916667        8.0
4  2008                  16.833333        7.6

UNRATE_PT means for each 100 active people, 6.6 are unemployed

In [18]:
df_btc_search = pd.read_csv("data/searchTerm_Bitcoin_2010_01_2025_12.csv")
df_btc_search["MONTH"] = pd.to_datetime(df_btc_search["MONTH"]).dt.to_period("M").astype(str)

df_btc_search.tail()

       MONTH  BTC_NEWS_SEARCH_PT
187  2025-08                  34
188  2025-09                  30
189  2025-10                  43
190  2025-11                  65
191  2025-12                  50

Search interest over a specific time period, displayed on a relative scale from 0 to 100, where 100 signifies the peak interest for the time period of the chart. A value of 50 indicates half the popularity of the peak, and 0 suggests insufficient data.

In [21]:
df_btc_price = pd.read_csv("data/dailyBitcoinPrice_2010_01_2025_12.csv", sep=";")

df_btc_price["DATE"] = pd.to_datetime(df_btc_price["timeOpen"]).dt.strftime("%Y-%m-%d") # Convert timeOpen to datetime

df_btc_price = df_btc_price[["DATE", "close", "volume"]] # Select only the columns we need
df_btc_price = df_btc_price.rename(columns={"DATE": "DATE","close": "CLOSE","volume": "VOLUME"}) # Rename columns

df_btc_price.head()

         DATE         CLOSE        VOLUME
0  2025-12-31  87508.825080  3.383021e+10
1  2025-12-30  88430.136120  3.558636e+10
2  2025-12-29  87138.143239  4.841163e+10
3  2025-12-28  87835.833511  1.515656e+10
4  2025-12-27  87802.155212  1.374120e+10

In [24]:
df_tesla_search = pd.read_csv("data/searchTerm_Tesla_2018_01_2025_12.csv")
df_tesla_search["MONTH"] = pd.to_datetime(df_tesla_search["MONTH"]).dt.to_period("M").astype(str) # Convert MONTH to period

df_tesla_search.tail()

      MONTH  TSLA_NEWS_SEARCH_PT
91  2025-08                   63
92  2025-09                   56
93  2025-10                   68
94  2025-11                   70
95  2025-12                   75

Search interest over a specific time period, displayed on a relative scale from 0 to 100, where 100 signifies the peak interest for the time period of the chart. A value of 50 indicates half the popularity of the peak, and 0 suggests insufficient data.

In [31]:
df_tsla = pd.read_csv("data/monthlyTslaPrice_2018_01_2025_12.csv")

df_tsla = df_tsla[["Date", "Close/Last"]] # Select only the columns we need
df_tsla["Date"] = pd.to_datetime(df_tsla["Date"]) # Convert Date to datetime

df_tsla["Close/Last"] = df_tsla["Close/Last"].replace({r"\$": ""}, regex=True).astype(float) # Remove '$' and convert to float

df_tsla_first = df_tsla[df_tsla["Date"].dt.day == 1] # Select only the first day of each month

df_tsla_first = df_tsla_first.rename(columns={"Date": "MONTH","Close/Last": "TSLA_USD_CLOSE"}) # Rename columns

df_tsla_first["MONTH"] = df_tsla_first["MONTH"].dt.to_period("M").astype(str) # Convert MONTH to YYYY-MM only
df_tsla_first = df_tsla_first.sort_values("MONTH") # Sort by MONTH

df_tsla_first

        MONTH  TSLA_USD_CLOSE
1989  2018-02         23.2833
1970  2018-03         22.0620
1928  2018-05         19.9947
1906  2018-06         19.4547
1864  2018-08         20.0560
...       ...             ...
168   2025-05        280.5200
127   2025-07        300.7100
105   2025-08        302.6300
63    2025-10        459.4600
21    2025-12        430.1400

[62 rows x 2 columns]

In [34]:
df_tesla = pd.merge(df_tesla_search, df_tsla_first, on="MONTH", how="inner")
df_tesla.tail()

      MONTH  TSLA_NEWS_SEARCH_PT  TSLA_USD_CLOSE
57  2025-05                   60          280.52
58  2025-07                   62          300.71
59  2025-08                   63          302.63
60  2025-10                   68          459.46
61  2025-12                   75          430.14

# Read the Data

In [35]:
df_tesla.head()
df_btc_search.head()
df_btc_price.head()
df_unemployment.head()

   YEAR  UE_BENEFITS_WEB_SEARCH_PT  UNRATE_PT
0  2004                   0.000000        6.6
1  2005                   8.333333        7.6
2  2006                  12.250000        7.6
3  2007                   8.916667        8.0
4  2008                  16.833333        7.6

# Data Exploration

### Tesla

**Challenge**: <br>
<ul>
<li>What are the shapes of the dataframes? </li>
<li>How many rows and columns? </li>
<li>What are the column names? </li>
<li>Complete the f-string to show the largest/smallest number in the search data column</li> 
<li>Try the <code>.describe()</code> function to see some useful descriptive statistics</li>
<li>What is the periodicity of the time series data (daily, weekly, monthly)? </li>
<li>What does a value of 100 in the Google Trend search popularity actually mean?</li>
</ul>

In [1]:
print(f'Largest value for Tesla in Web Search: ')
print(f'Smallest value for Tesla in Web Search: ')

Largest value for Tesla in Web Search:
Smallest value for Tesla in Web Search:

### Unemployment Data

In [2]:
print('Largest value for "Unemployemnt Benefits" '
      f'in Web Search: ')

Largest value for "Unemployemnt Benefits" in Web Search:

### Bitcoin

In [6]:
print(f'largest BTC News Search: ')

largest BTC News Search:

# Data Cleaning

### Check for Missing Values

**Challenge**: Are there any missing values in any of the dataframes? If so, which row/rows have missing values? How many missing values are there?

In [7]:
print(f'Missing values for Tesla?: ')
print(f'Missing values for U/E?: ')
print(f'Missing values for BTC Search?: ')

Missing values for Tesla?:
Missing values for U/E?:
Missing values for BTC Search?:

In [8]:
print(f'Missing values for BTC price?: ')

Missing values for BTC price?:

In [5]:
print(f'Number of missing values: ')

Number of missing values:

**Challenge**: Remove any missing values that you found.

### Convert Strings to DateTime Objects

**Challenge**: Check the data type of the entries in the DataFrame MONTH or DATE columns. Convert any strings in to Datetime objects. Do this for all 4 DataFrames. Double check if your type conversion was successful.

### Converting from Daily to Monthly Data

[Pandas .resample() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) <br>

# Data Visualisation

### Notebook Formatting & Style Helpers

In [22]:
# Create locators for ticks on the time axis

In [21]:
# Register date converters to avoid warning messages

### Tesla Stock Price v.s. Search Volume

**Challenge:** Plot the Tesla stock price against the Tesla search volume using a line chart and two different axes. Label one axis 'TSLA Stock Price' and the other 'Search Trend'.

**Challenge**: Add colours to style the chart. This will help differentiate the two lines and the axis labels. Try using one of the blue [colour names](https://matplotlib.org/3.1.1/gallery/color/named_colors.html) for the search volume and a HEX code for a red colour for the stock price. 
<br>
<br>
Hint: you can colour both the [axis labels](https://matplotlib.org/3.3.2/api/text_api.html#matplotlib.text.Text) and the [lines](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) on the chart using keyword arguments (kwargs).

**Challenge**: Make the chart larger and easier to read. 
1. Increase the figure size (e.g., to 14 by 8). 
2. Increase the font sizes for the labels and the ticks on the x-axis to 14. 
3. Rotate the text on the x-axis by 45 degrees. 
4. Make the lines on the chart thicker. 
5. Add a title that reads 'Tesla Web Search vs Price'
6. Keep the chart looking sharp by changing the dots-per-inch or [DPI value](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.figure.html). 
7. Set minimum and maximum values for the y and x axis. Hint: check out methods like [set_xlim()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_xlim.html). 
8. Finally use [plt.show()](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.show.html) to display the chart below the cell instead of relying on the automatic notebook output.

How to add tick formatting for dates on the x-axis.

### Bitcoin (BTC) Price v.s. Search Volume

**Challenge**: Create the same chart for the Bitcoin Prices vs. Search volumes. <br>
1. Modify the chart title to read 'Bitcoin News Search vs Resampled Price' <br>
2. Change the y-axis label to 'BTC Price' <br>
3. Change the y- and x-axis limits to improve the appearance <br>
4. Investigate the [linestyles](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.plot.html ) to make the BTC price a dashed line <br>
5. Investigate the [marker types](https://matplotlib.org/3.2.1/api/markers_api.html) to make the search datapoints little circles <br>
6. Were big increases in searches for Bitcoin accompanied by big increases in the price?

### Unemployement Benefits Search vs. Actual Unemployment in the U.S.

**Challenge** Plot the search for "unemployment benefits" against the unemployment rate. 
1. Change the title to: Monthly Search of "Unemployment Benefits" in the U.S. vs the U/E Rate <br>
2. Change the y-axis label to: FRED U/E Rate <br>
3. Change the axis limits <br>
4. Add a grey [grid](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.grid.html) to the chart to better see the years and the U/E rate values. Use dashes for the line style<br> 
5. Can you discern any seasonality in the searches? Is there a pattern?

**Challenge**: Calculate the 3-month or 6-month rolling average for the web searches. Plot the 6-month rolling average search data against the actual unemployment. What do you see in the chart? Which line moves first?

### Including 2020 in Unemployment Charts

**Challenge**: Read the data in the 'UE Benefits Search vs UE Rate 2004-20.csv' into a DataFrame. Convert the MONTH column to Pandas Datetime objects and then plot the chart. What do you see?